name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt -r requirements-dev.txt
      - name: Run tests
        run: pytest backend/tests
      - name: Run Bandit security scan
        run: bandit -r backend/app -ll
      - name: Safety vulnerability check
        run: safety check -r backend/requirements.txt